version: '3.6'  
services:  
  app:
    build: .
    depends_on:
      - redis
    env_file:
      - .env
    environment:
        BUCKET_NAME: ${BUCKET_NAME}
        REGION: "${REGION}"
        aws_access_key_id: "${aws_access_key_id}"
        aws_secret_access_key: "${aws_secret_access_key}" 
         
        REDIS_HOST: redis

    ports:
      - "5000:5000"
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
  
volumes:  
  redis_data:
