version: '3.6'  
services:  
  app:
    build: .
    depends_on:
      - redis
    environment:
        BUCKET_NAME: "analytics-pipeline-cmucybercom"
        REGION: "us-east-1"
        ACCOUNT_ID: "444558491062"
        #credentials / manual config should be moved into a .env file for build time.
        aws_access_key_id: ""
        aws_secret_access_key: "" 
         
        REDIS_HOST: redis

    ports:
      - "5000:5000"
  redis:
    image: redis:3.2-alpine
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:latest
    ports:
     - "80:80"
volumes:  
  redis_data: